title: 我的博客
description: 记录与分享我的想法和心得
author: 博主
email: your-email@example.com
baseurl: "/blog.github.io" # 修改为你的子路径
url: "https://codyshen0000.github.io" # 修改为你的实际GitHub用户名

# 社交媒体链接
twitter_username: 
github_username: 
weibo_username: 

# 博客设置
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md 